import { Construct, IConstruct } from 'constructs';
import { ApiObject } from './api-object';
import { App } from './app';
import { Names } from './names';

const CHART_SYMBOL = Symbol.for('cdk8s.Chart');
const CRONJOB = 'CronJob';

export interface ChartProps {
  /**
   * The default namespace for all objects defined in this chart (directly or
   * indirectly). This namespace will only apply to objects that don't have a
   * `namespace` explicitly defined for them.
   *
   * @default - no namespace is synthesized (usually this implies "default")
   */
  readonly namespace?: string;

  /**
   * Labels to apply to all resources in this chart.
   *
   * @default - no common labels
   */
  readonly labels?: { [name: string]: string };

  /**
   * The autogenerated resource name by default is suffixed with a stable hash
   * of the construct path. Setting this property to true drops the hash suffix.
   *
   * @default false
   */
  readonly disableResourceNameHashes?: boolean;

}

export class Chart extends Construct {
  /**
   * Return whether the given object is a Chart.
   *
   * We do attribute detection since we can't reliably use 'instanceof'.
   */
  public static isChart(x: any): x is Chart {
    return x !== null && typeof(x) === 'object' && CHART_SYMBOL in x;
  }

  /**
   * Implements `instanceof Chart` using the more reliable `Chart.isChart` static method
   *
   * @param o The object to check
   * @internal
   */
  static [Symbol.hasInstance](o: unknown) {
    return Chart.isChart(o);
  }

  /**
   * Finds the chart in which a node is defined.
   * @param c a construct node
   */
  public static of(c: IConstruct): Chart {
    if (Chart.isChart(c)) {
      return c;
    }

    const parent = c.node.scope as Construct;
    if (!parent) {
      throw new Error('cannot find a parent chart (directly or indirectly)');
    }

    return Chart.of(parent);
  }

  /**
   * The default namespace for all objects in this chart.
   */
  public readonly namespace?: string;

  /**
   * Chart-level labels.
   */
  private readonly _labels?: { [name: string]: string };

  /**
   * Determines if resource names in the chart have the suffixed hash.
   */
  private readonly _disableResourceNameHashes?: boolean;

  constructor(scope: Construct, id: string, props: ChartProps = { }) {
    super(scope, id);
    this.namespace = props.namespace;
    this._labels = props.labels ?? {};
    this._disableResourceNameHashes = props.disableResourceNameHashes ?? false;

    Object.defineProperty(this, CHART_SYMBOL, { value: true });
  }

  /**
   * Labels applied to all resources in this chart.
   *
   * This is an immutable copy.
   */
  public get labels(): { [name: string]: string } {
    return { ...this._labels };
  }

  /**
   * Generates a app-unique name for an object given it's construct node path.
   *
   * Different resource types may have different constraints on names
   * (`metadata.name`). The previous version of the name generator was
   * compatible with DNS_SUBDOMAIN but not with DNS_LABEL.
   *
   * For example, `Deployment` names must comply with DNS_SUBDOMAIN while
   * `Service` names must comply with DNS_LABEL.
   *
   * Since there is no formal specification for this, the default name
   * generation scheme for kubernetes objects in cdk8s was changed to DNS_LABEL,
   * since it’s the common denominator for all kubernetes resources
   * (supposedly).
   *
   * You can override this method if you wish to customize object names at the
   * chart level.
   *
   * @param apiObject The API object to generate a name for.
   */
  public generateObjectName(apiObject: ApiObject) {
    return Names.toDnsLabel(apiObject, {
      includeHash: !this._disableResourceNameHashes,
      maxLen: apiObject.kind == CRONJOB ? 52 : undefined,
    });
  }

  /**
   * Create a dependency between this Chart and other constructs.
   * These can be other ApiObjects, Charts, or custom.
   *
   * @param dependencies the dependencies to add.
   */
  public addDependency(...dependencies: IConstruct[]) {
    this.node.addDependency(...dependencies);
  }

  /**
   * Renders this chart to a set of Kubernetes JSON resources.
   * @returns array of resource manifests
   */
  public toJson(): any[] {
    return App._synthChart(this);
  }

  /**
   * Returns all the included API objects.
   */
  get apiObjects(): ApiObject[] {
    return this.node.children.filter((o): o is ApiObject => o instanceof ApiObject);
  }
}
